server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate: 
        default_schema: master_app
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: eleg
    password: eleg
    
jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities: 
    key: roles
  header:
    string: Authorization